### ISSUE TITLE
saneyaml requires too precise version of PyYAML, can't be installed easily with pip on real systems

### ISSUE THREAD

**Issue by dankegel** [nexB/saneyaml#1]
In pristine systems, it's fine to depend on a precise version of PyYAML.
But installing scancode-toolkit on systems which already have PyYAML 5.1 installed
generates a broken scancode:

```
$ ~/.local/bin/scancode --help
pluggy.manager.PluginValidationError: Plugin 'json-pp' could not be loaded: (PyYAML 5.1 (/home/ubuntu/.local/lib/python2.7/site-packages), Requirement.parse('PyYAML<=3.13,>=3.11'))!
```

Can that requirement be loosened to support current PyYAML, too, please?

**Comment by pombredanne** [comment]
@dankegel  
saneyaml has some deps on quasi non-API code in PyYAML ... and this tight version requirements was there to avoid problems in cases that commits would ever restart on PyYAML and they just did... The newest version 5 makes saneyaml tests fail for sure and need to be fixed first

**Comment by pombredanne** [comment]
This is merged at last!
Thank you for your patience .
