### ISSUE TITLE
pip should be added as a dependency to install_requires

### ISSUE THREAD

**Issue by knobix** [nexB/saneyaml#2]
**OS:** FreeBSD 11.2-RELEASE-p9 amd64 (applies also for i386 and 12.0-RELEASE-p3)
**Python version:** 2.7.16 (applies also for 3.6.8)
**saneyaml version:** 0.1

If saneyaml is built in a clean (e.g FreeBSD jail) environment, not all dependencies are resolved when testing the Python package by importing it:

`>>> import saneyaml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/saneyaml.py", line 27, in <module>
    from pip._vendor.distlib.compat import OrderedDict
 ImportError: No module named pip._vendor.distlib.compat
`

In such an environment only the Python runtime is installed together with the Python packages "setuptools" (automatically done by the FreeBSD ports framework) and "yaml" (installed via the Makefile of the port itself).

**Comment by pombredanne** [comment]
@knobix what a mistake I made there!
we should not have this dependency at all
Thank you for reporting this and this needs to be fixed ASAP.

@dankegel ^ I wonder if this was not a source of some of your problems too

**Comment by pombredanne** [comment]
@knobix this is fixed now and released as https://pypi.org/project/saneyaml/
There is no dep on pip needed!
Thank you ++ for this report

**Comment by knobix** [comment]
Thank you for the quick fix!
