### ISSUE TITLE
Document support for PyYAML 6

### ISSUE THREAD

**Issue by mwgamble** [nexB/saneyaml#7]
This library seems to work fine with PyYAML 6, based on my limited testing. It would be good to document that that's supported.

**Comment by pombredanne** [comment]
Thanks ... I documented this in #8 
https://github.com/nexB/saneyaml/pull/8/commits/c3e488e4e6a5765f76babb0c73442f07ba3bff2e

**Comment by pombredanne** [comment]
Fixed in release 0.6.0
Thanks for the report!
